/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 */

package com.mycompany.icetask2;

import java.util.Scanner;

/**
 *
 * @author asand
 */
public class IceTask2 {

    interface IVehicleDealer { // Adapted from: W3Schools
                               // Reference: https://www.w3schools.com/java/java_interface.asp
        String generateQuote();
}

static abstract class Employee {

    protected String name;
    protected String employeeId;
    protected double baseSalary;

public Employee(String name, String employeeId, double baseSalary) {
    this.name = name;
    this.employeeId = employeeId;
    this.baseSalary = baseSalary;
}

public abstract double calculateCommission(); // Adapted from: W3Schools
                                              // Reference: https://www.w3schools.com/java/java_abstract.asp
}

static class SalesAgent extends Employee implements IVehicleDealer {

    private int vehiclesSold;
    private double commissionRate;

public SalesAgent(String name, String employeeId, double baseSalary,
    int vehiclesSold, double commissionRate) {

    super(name, employeeId, baseSalary);
    this.vehiclesSold = vehiclesSold;
    this.commissionRate = commissionRate;
}

        @Override // Adapted from: GeeksforGeeks
                  // Reference: https://www.geeksforgeeks.org/java/overriding-in-java/
public double calculateCommission() {
    return vehiclesSold * commissionRate;
}

        @Override // Adapted from: GeeksforGeeks
                  // Reference: https://www.geeksforgeeks.org/java/overriding-in-java/
public String generateQuote() {
    return "Quote generated by " + name + " (Agent ID: " + employeeId + "). Please contact the dealership for full pricing details.";
}

public void printReport() {
    double commission = calculateCommission();
    double totalEarnings = baseSalary + commission;

        System.out.println("----------------------------------------");
        System.out.println("Agent Name     : " + name);
        System.out.println("Employee ID    : " + employeeId);
        System.out.printf("Base Salary    : R%.2f%n", baseSalary);  // Adapted from: W3Schools
                                                                    // Reference: https://www.w3schools.com/java/ref_output_printf.asp
        System.out.println("Vehicles Sold  : " + vehiclesSold);
        System.out.printf("Commission     : R%.2f%n", commission);  // Adapted from: W3Schools
                                                                    // Reference: https://www.w3schools.com/java/ref_output_printf.asp
        System.out.printf("Total Earnings : R%.2f%n", totalEarnings);// Adapted from: W3Schools
                                                                     // Reference: https://www.w3schools.com/java/ref_output_printf.asp

    if (commission > 10000.0) {
        System.out.println(">>> Top Seller! <<<");
}

        System.out.println("----------------------------------------");
}
}

public static void main(String[] args) {

        Scanner scanner = new Scanner(System.in);

        System.out.println("========================================");
        System.out.println("     DEALERSHIP SALES - DATA ENTRY");
        System.out.println("========================================");
        System.out.print("How many sales agents would you like to enter? \n");
    int numAgents = scanner.nextInt();
        scanner.nextLine();

        SalesAgent[] agents = new SalesAgent[numAgents];

    for (int i = 0; i < numAgents; i++) {
        System.out.println("\n--- Agent " + (i + 1) + " ---");

        System.out.print("Name: ");
        String name = scanner.nextLine();

        System.out.print("Employee ID: ");
        String employeeId = scanner.nextLine();

        System.out.print("Base Salary (R): ");
    double baseSalary = scanner.nextDouble();

        System.out.print("Vehicles Sold: ");
    int vehiclesSold = scanner.nextInt();

        System.out.print("Commission Rate per vehicle (R): ");
    double commissionRate = scanner.nextDouble();
        scanner.nextLine();

        agents[i] = new SalesAgent(name, employeeId, baseSalary,
        vehiclesSold, commissionRate);
}

        scanner.close();

        System.out.println("\n========================================");
        System.out.println("        DEALERSHIP SALES REPORT");
        System.out.println("========================================");

    for (int i = 0; i < agents.length; i++) {
        agents[i].printReport();
}
}
}